import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Foundations - Attune',
  description:
    'Attune Foundations - The theoretical and behavioral basis of Attune self-regulation training.',
}

export default function Foundations() {
  return (
    <main>
      <section className="mb-20">
        <h1 className="mb-2 bg-gradient-to-br from-slate-900 to-slate-600 bg-clip-text text-5xl font-light leading-tight text-transparent dark:from-cyan-50 dark:to-cyan-200 md:text-7xl">
          Foundations
        </h1>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Attune is grounded in contemporary neuroscience, cognitive science,
          and learning theory.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Its design reflects how biological systems regulate internal state
          through{' '}
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            feedback, prediction, and adaptation
          </strong>
          , rather than suppression, reframing, or willpower.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Regulation is treated as a{' '}
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            trainable capability
          </strong>
          , not a trait or diagnosis.
        </p>

        <h2 className="mb-4 mt-8 text-3xl font-light tracking-wide text-slate-900 small-caps dark:text-cyan-50">
          Core Concepts
        </h2>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Interoception
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Interoception
          </strong>{' '}
          is the nervous system’s capacity to sense internal physiological
          signals, including respiration, heart rate, muscle tension, visceral
          sensation, and thermal state.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          These signals form the raw inputs used to construct emotional and
          motivational states.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Improving interoceptive resolution increases the precision and
          timeliness of regulation.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Affect Labeling
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Affect labeling
          </strong>{' '}
          is the process of applying a precise categorical label to an internal
          state.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Accurate labeling recruits prefrontal regulatory circuits and reduces
          ambiguity in state prediction. Precision matters: coarse labels
          preserve uncertainty; specific labels constrain it.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Allostasis
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Allostasis
          </strong>{' '}
          refers to stability achieved through change.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Rather than returning to a fixed equilibrium, biological systems
          continuously predict demand and adjust internal parameters in advance.
          Regulation is therefore anticipatory, not reactive.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Predictive Coding
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Predictive coding
          </strong>{' '}
          models the brain as an inference system.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Internal states are generated by top-down predictions and updated
          through bottom-up sensory error signals. Regulation improves when
          prediction errors are detected earlier and corrected with smaller
          adjustments.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Emotional Granularity
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Emotional granularity
          </strong>{' '}
          describes the ability to distinguish between closely related affective
          states.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Higher granularity is associated with improved flexibility,
          decision-making, and resilience under stress.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Autonomic Regulation
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            Autonomic regulation
          </strong>{' '}
          refers to the modulation of sympathetic and parasympathetic activity.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Attune does not aim to suppress arousal, but to shift state
          efficiently and proportionally to context.
        </p>

        <h2 className="mb-4 mt-8 text-3xl font-light tracking-wide text-slate-900 small-caps dark:text-cyan-50">
          Habit Formation Through Cueing
        </h2>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Attune treats habit formation as a{' '}
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            biological learning process
          </strong>
          , not a motivational one.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Rather than relying on reminders or discipline, Attune emphasizes:
        </p>
        <ul className="mb-6 list-disc pl-5">
          <li className="mb-2 pl-2">intentionally provoked internal cues</li>
          <li className="mb-2 pl-2">repeated exposure under real conditions</li>
          <li className="mb-2 pl-2">
            closed-loop feedback at the moment of state change
          </li>
        </ul>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Over time, regulatory responses become:
        </p>
        <ul className="mb-6 list-disc pl-5">
          <li className="mb-2 pl-2">faster</li>
          <li className="mb-2 pl-2">lower-effort</li>
          <li className="mb-2 pl-2">more context-sensitive</li>
        </ul>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Habits emerge as a byproduct of correct repetition, not as a goal
          pursued directly.
        </p>

        <h2 className="mb-4 mt-8 text-3xl font-light tracking-wide text-slate-900 small-caps dark:text-cyan-50">
          Levels of Engagement
        </h2>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Attune is designed to support{' '}
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            multiple levels of engagement
          </strong>
          , each serving a distinct role in long-term regulation.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          These levels are not hierarchical in value; they are complementary.
        </p>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          In-the-Moment Engagement
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Brief, real-time interactions triggered by internal cues.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Purpose:
        </p>
        <ul className="mb-6 list-disc pl-5">
          <li className="mb-2 pl-2">immediate state influence</li>
          <li className="mb-2 pl-2">early error correction</li>
          <li className="mb-2 pl-2">preservation of agency under load</li>
        </ul>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Reflective Engagement
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Short periods of review or consolidation after the fact.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Purpose:
        </p>
        <ul className="mb-6 list-disc pl-5">
          <li className="mb-2 pl-2">reinforce learning</li>
          <li className="mb-2 pl-2">refine labeling accuracy</li>
          <li className="mb-2 pl-2">improve future detection</li>
        </ul>

        <h3 className="mb-2 text-2xl font-normal text-slate-900 dark:text-cyan-50">
          Structural Engagement
        </h3>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Occasional, deliberate training outside of reactive moments.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Purpose:
        </p>
        <ul className="mb-6 list-disc pl-5">
          <li className="mb-2 pl-2">expand regulatory repertoire</li>
          <li className="mb-2 pl-2">increase baseline sensitivity</li>
          <li className="mb-2 pl-2">prepare for unfamiliar states</li>
        </ul>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Each level contributes differently to the same outcome: improved
          adaptive regulation.
        </p>

        <h2 className="mb-4 mt-8 text-3xl font-light tracking-wide text-slate-900 small-caps dark:text-cyan-50">
          Design Position
        </h2>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          Attune treats emotional and cognitive states as{' '}
          <strong className="font-semibold text-slate-900 dark:text-cyan-50">
            physiological signals governed by control systems
          </strong>
          , not narratives to be interpreted or problems to be eliminated.
        </p>
        <p className="mb-6 max-w-prose text-slate-900 dark:text-cyan-50">
          The Attune Loop is the operational expression of these foundations.
        </p>
      </section>
    </main>
  )
}
